package com.kaddy.model.enums;

public enum ServiceCategory {
    CONSULTATION, LABORATORY, RADIOLOGY, PHARMACY, PROCEDURE, SURGERY, ROOM_CHARGES, NURSING, ICU_CHARGES, EMERGENCY, AMBULANCE, PHYSIOTHERAPY, DIET, EQUIPMENT, CONSUMABLES, MISCELLANEOUS
}
