package com.kaddy.model.enums;

public enum SurgeryType {
    GENERAL_SURGERY,
    CARDIAC_SURGERY,
    ORTHOPEDIC_SURGERY,
    NEUROSURGERY,
    PLASTIC_SURGERY,
    GYNECOLOGICAL_SURGERY,
    UROLOGICAL_SURGERY,
    OPHTHALMIC_SURGERY,
    ENT_SURGERY,
    EMERGENCY_SURGERY,
    OTHER
}
