package com.kaddy.model.enums;

public enum WardType {
    GENERAL, ICU, NICU, PICU, CCU, HDU, EMERGENCY, ISOLATION, MATERNITY, PEDIATRIC, PSYCHIATRIC, SURGICAL, ORTHOPEDIC, ONCOLOGY, CARDIOLOGY, NEUROLOGY, BURNS, DIALYSIS
}
