export const hasPermission = (permission, userPermissions) => {
  if (!userPermissions || !Array.isArray(userPermissions)) {
    return false;
  }
  return userPermissions.includes(permission);
};

export const hasAnyPermission = (permissions, userPermissions) => {
  if (!userPermissions || !Array.isArray(userPermissions)) {
    return false;
  }
  return permissions.some((permission) => userPermissions.includes(permission));
};

export const hasAllPermissions = (permissions, userPermissions) => {
  if (!userPermissions || !Array.isArray(userPermissions)) {
    return false;
  }
  return permissions.every((permission) =>
    userPermissions.includes(permission)
  );
};

export const hasRole = (role, userRole) => {
  return userRole === role;
};
export const hasAnyRole = (roles, userRole) => {
  return roles.includes(userRole);
};

export const PERMISSIONS = {
  VIEW_ALL_PATIENTS: "VIEW_ALL_PATIENTS",
  VIEW_ASSIGNED_PATIENTS: "VIEW_ASSIGNED_PATIENTS",
  ADD_PATIENT: "ADD_PATIENT",
  EDIT_PATIENT: "EDIT_PATIENT",
  DELETE_PATIENT: "DELETE_PATIENT",
  VIEW_PATIENT_DETAILS: "VIEW_PATIENT_DETAILS",
  VIEW_PATIENT_REPORTS: "VIEW_PATIENT_REPORTS",

  VIEW_DOCTORS: "VIEW_DOCTORS",
  ADD_DOCTOR: "ADD_DOCTOR",
  EDIT_DOCTOR: "EDIT_DOCTOR",
  DELETE_DOCTOR: "DELETE_DOCTOR",

  VIEW_NURSES: "VIEW_NURSES",
  ADD_NURSE: "ADD_NURSE",
  EDIT_NURSE: "EDIT_NURSE",
  DELETE_NURSE: "DELETE_NURSE",

  VIEW_LAB_TECHNICIANS: "VIEW_LAB_TECHNICIANS",
  ADD_LAB_TECHNICIAN: "ADD_LAB_TECHNICIAN",
  EDIT_LAB_TECHNICIAN: "EDIT_LAB_TECHNICIAN",
  DELETE_LAB_TECHNICIAN: "DELETE_LAB_TECHNICIAN",

  VIEW_RECEPTIONISTS: "VIEW_RECEPTIONISTS",
  ADD_RECEPTIONIST: "ADD_RECEPTIONIST",
  EDIT_RECEPTIONIST: "EDIT_RECEPTIONIST",
  DELETE_RECEPTIONIST: "DELETE_RECEPTIONIST",

  VIEW_PHARMACISTS: "VIEW_PHARMACISTS",
  ADD_PHARMACIST: "ADD_PHARMACIST",
  EDIT_PHARMACIST: "EDIT_PHARMACIST",
  DELETE_PHARMACIST: "DELETE_PHARMACIST",

  ASSIGN_DOCTOR_TO_PATIENT: "ASSIGN_DOCTOR_TO_PATIENT",
  REMOVE_DOCTOR_FROM_PATIENT: "REMOVE_DOCTOR_FROM_PATIENT",
  VIEW_ASSIGNMENTS: "VIEW_ASSIGNMENTS",

  VIEW_APPOINTMENTS: "VIEW_APPOINTMENTS",
  BOOK_APPOINTMENT: "BOOK_APPOINTMENT",
  CANCEL_APPOINTMENT: "CANCEL_APPOINTMENT",
  RESCHEDULE_APPOINTMENT: "RESCHEDULE_APPOINTMENT",

  VIEW_MEDICATIONS: "VIEW_MEDICATIONS",
  ADD_MEDICATION: "ADD_MEDICATION",
  EDIT_MEDICATION: "EDIT_MEDICATION",
  DELETE_MEDICATION: "DELETE_MEDICATION",
  PRESCRIBE_MEDICATION: "PRESCRIBE_MEDICATION",

  VIEW_MEDICATION_REQUESTS: "VIEW_MEDICATION_REQUESTS",
  APPROVE_MEDICATION_REQUEST: "APPROVE_MEDICATION_REQUEST",

  VIEW_FOLLOW_UPS: "VIEW_FOLLOW_UPS",
  ADD_FOLLOW_UP: "ADD_FOLLOW_UP",
  EDIT_FOLLOW_UP: "EDIT_FOLLOW_UP",
  DELETE_FOLLOW_UP: "DELETE_FOLLOW_UP",

  VIEW_LAB_TESTS: "VIEW_LAB_TESTS",
  ORDER_LAB_TEST: "ORDER_LAB_TEST",
  UPLOAD_LAB_RESULTS: "UPLOAD_LAB_RESULTS",
  VIEW_LAB_RESULTS: "VIEW_LAB_RESULTS",

  VIEW_NOTIFICATIONS: "VIEW_NOTIFICATIONS",

  VIEW_MONITORING: "VIEW_MONITORING",
  VIEW_SYSTEM_STATS: "VIEW_SYSTEM_STATS",

  VIEW_PROFILE: "VIEW_PROFILE",
  EDIT_PROFILE: "EDIT_PROFILE",

  VIEW_OWN_PROFILE: "VIEW_OWN_PROFILE",
  VIEW_OWN_APPOINTMENTS: "VIEW_OWN_APPOINTMENTS",
  VIEW_OWN_LAB_TESTS: "VIEW_OWN_LAB_TESTS",
  VIEW_OWN_PRESCRIPTIONS: "VIEW_OWN_PRESCRIPTIONS",
  VIEW_OWN_MEDICAL_RECORDS: "VIEW_OWN_MEDICAL_RECORDS",

  VIEW_PENDING_REGISTRATIONS: "VIEW_PENDING_REGISTRATIONS",
  APPROVE_DOCTOR_REGISTRATION: "APPROVE_DOCTOR_REGISTRATION",
  APPROVE_NURSE_REGISTRATION: "APPROVE_NURSE_REGISTRATION",
  APPROVE_RECEPTIONIST_REGISTRATION: "APPROVE_RECEPTIONIST_REGISTRATION",
  APPROVE_SUPERVISOR_REGISTRATION: "APPROVE_SUPERVISOR_REGISTRATION",
  REJECT_REGISTRATION: "REJECT_REGISTRATION",
};

export const ROLES = {
  ADMIN: "ADMIN",
  DOCTOR: "DOCTOR",
  DOCTOR_SUPERVISOR: "DOCTOR_SUPERVISOR",
  NURSE: "NURSE",
  NURSE_MANAGER: "NURSE_MANAGER",
  NURSE_SUPERVISOR: "NURSE_SUPERVISOR",
  LAB_TECHNICIAN: "LAB_TECHNICIAN",
  PHARMACIST: "PHARMACIST",
  RECEPTIONIST: "RECEPTIONIST",
  PATIENT: "PATIENT",
};
